[python 数据科学](https://www.coursera.org/learn/python-data-analysis)

## python fundamentals

序列[]{}()   
迭代遍历for x in ..   
切片[:-1]   
list, str, tuple, dict

In [8]:
# func 默认参数
def add_nums(a, b, c=None):
    if c == None:
        return a + b
    return a + b +c

add_nums(1, 2)

3

In [2]:
add_nums('a', 'b', 'd')

'abd'

In [3]:
class Tree:
    def __init__(self, date=None, left=None, right=None):
        self.date = date
        self.left = left
        self.right = right

def inv(node):  # functional program
    if node is None:
        return None
    return Tree(node.date, inv(node.right), inv(node.left))

bt = Tree(1, Tree(2, Tree(4), Tree(5)), Tree(3, Tree(6)))

In [1]:
for i in range(5):
    print((lambda x : x ** 2)(i))

0
1
4
9
16


In [1]:
import csv
with open('mpg.csv') as csvfile:
    mpg = csv.DictReader(csvfile)  # 字典形式
    for row in mpg:
        print(row['manufacturer'], row['year'])
row.items()

audi 1999
audi 1999
audi 2008
audi 2008
audi 1999
audi 1999
audi 2008
audi 1999
audi 1999
audi 2008
audi 2008
audi 1999
audi 1999
audi 2008
audi 2008
audi 1999
audi 2008
audi 2008
chevrolet 2008
chevrolet 2008
chevrolet 2008
chevrolet 1999
chevrolet 2008
chevrolet 1999
chevrolet 1999
chevrolet 2008
chevrolet 2008
chevrolet 2008
chevrolet 2008
chevrolet 2008
chevrolet 1999
chevrolet 1999
chevrolet 1999
chevrolet 2008
chevrolet 1999
chevrolet 2008
chevrolet 2008
dodge 1999
dodge 1999
dodge 1999
dodge 1999
dodge 2008
dodge 2008
dodge 2008
dodge 1999
dodge 1999
dodge 2008
dodge 2008
dodge 2008
dodge 2008
dodge 1999
dodge 1999
dodge 2008
dodge 2008
dodge 2008
dodge 1999
dodge 1999
dodge 1999
dodge 2008
dodge 2008
dodge 2008
dodge 1999
dodge 2008
dodge 1999
dodge 2008
dodge 2008
dodge 2008
dodge 2008
dodge 2008
dodge 2008
dodge 1999
dodge 1999
dodge 2008
dodge 1999
ford 1999
ford 1999
ford 2008
ford 1999
ford 1999
ford 1999
ford 2008
ford 2008
ford 1999
ford 1999
ford 1999
ford 1999
ford 199

odict_items([('', '234'), ('manufacturer', 'volkswagen'), ('model', 'passat'), ('displ', '3.6'), ('year', '2008'), ('cyl', '6'), ('trans', 'auto(s6)'), ('drv', 'f'), ('cty', '17'), ('hwy', '26'), ('fl', 'p'), ('class', 'midsize')])

In [5]:
with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))  # 转list 可索引
mpg[2]['year']

'2008'

In [6]:
set(c['manufacturer'] for c in mpg)

{'audi',
 'chevrolet',
 'dodge',
 'ford',
 'honda',
 'hyundai',
 'jeep',
 'land rover',
 'lincoln',
 'mercury',
 'nissan',
 'pontiac',
 'subaru',
 'toyota',
 'volkswagen'}

## numpy

In [7]:
import numpy as np
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.arange(20, 40, 2).reshape(2, 5)

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [11]:
x = np.linspace(20, 40, 10)  # nums=10 in [20,40)
x.resize(5, 2)  # x has changed
x

array([[20.        , 22.22222222],
       [24.44444444, 26.66666667],
       [28.88888889, 31.11111111],
       [33.33333333, 35.55555556],
       [37.77777778, 40.        ]])

In [16]:
print(x.mean())
print(x.argmax())
x[:2, 1]

30.0
9


array([22.22222222, 26.66666667])

## pandas
Series DataFrame

In [3]:
import pandas as pd
import numpy as np

In [4]:
plan = pd.Series(['math', 'algorithm', 'write'], index=['Sat.', 'Sun.', 'Mon.'])  ## creat
plan

Sat.         math
Sun.    algorithm
Mon.        write
dtype: object

In [5]:
plan.index

Index(['Sat.', 'Sun.', 'Mon.'], dtype='object')

In [8]:
plan.iloc[0]  # attribute use [], not method ()

'math'

In [9]:
plan.loc['Mon.']

'write'

In [15]:
many = pd.Series(np.random.randint(1000, 2001, 1000000))
many.head()

0    1966
1    1073
2    1441
3    1408
4    1739
dtype: int32

In [18]:
%%timeit
total = np.sum(many)

7.65 ms ± 230 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
many += 1986  # broadcast
many.head(2)

0    3952
1    3059
dtype: int32

In [23]:
plan.loc[7] = 'rest'
plan.loc[8] = None
plan

Sat.         math
Sun.    algorithm
Mon.        write
7            rest
8            None
dtype: object

In [25]:
plan2 = pd.Series({'Sat.': 'sleep',
                   'Sun.': 'eat',
                   'Mon.': 'play'})

In [27]:
plan3 = pd.Series({'Sat.': 'work',
                   'Sun.': 'work',
                   'Mon.': 'rest'})

In [28]:
df = pd.DataFrame([plan, plan2, plan3], index=['dy', 'fhp', 'fhp'])  ## creat
df

Sat.       Sun.   Mon.     7   8
dy    math  algorithm  write  rest NaN
fhp  sleep        eat   play   NaN NaN
fhp   work       work   rest   NaN NaN

In [36]:
df.loc['fhp']

Sat.  Sun.  Mon.    7   8
fhp  sleep   eat  play  NaN NaN
fhp   work  work  rest  NaN NaN

In [37]:
df.loc['dy', 'Mon.']

'write'

In [38]:
df.T.loc['Sat.']

dy      math
fhp    sleep
fhp     work
Name: Sat., dtype: object

In [40]:
df['Sat.']

dy      math
fhp    sleep
fhp     work
Name: Sat., dtype: object

In [41]:
df.loc[ : , ['Sun.', 'Mon.']]

Sun.   Mon.
dy   algorithm  write
fhp        eat   play
fhp       work   rest

In [42]:
droped_df = df.drop('fhp') ## drop row
droped_df

Sat.       Sun.   Mon.     7   8
dy  math  algorithm  write  rest NaN

In [43]:
df

Sat.       Sun.   Mon.     7   8
dy    math  algorithm  write  rest NaN
fhp  sleep        eat   play   NaN NaN
fhp   work       work   rest   NaN NaN

In [45]:
del droped_df[7]  ## drop col
droped_df

Sat.       Sun.   Mon.   8
dy  math  algorithm  write NaN

In [49]:
del df[7]
del df[8]
df['Tom.'] = 'talk'  ## add col

In [50]:
df

Sat.       Sun.   Mon.  Tom.
dy    math  algorithm  write  talk
fhp  sleep        eat   play  talk
fhp   work       work   rest  talk

In [62]:
!copy D:\Users\Documents\Code_\Python\helloworld\pokemon.csv .

已复制         1 个文件。


In [77]:
df = pd.read_csv('pokemon.csv', index_col = 'name')
df.head()

cp      attack  attack_new
name                                
Pidgey1  384  Aerial Ace  Air Cutter
Pidgey2  366     Twister  Air Cutter
Pidgey3  353  Aerial Ace  Air Cutter
Pidgey4  338  Air Cutter  Air Cutter
Pidgey5  242  Air Cutter     Twister

In [68]:
df['cp'] > 350  # bool mask

name
Pidgey1      True
Pidgey2      True
Pidgey3      True
Pidgey4     False
Pidgey5     False
Pidgey6     False
Pidgey7     False
Pidgey8     False
Pidgey9     False
Pidgey10    False
Eevee1       True
Eevee3       True
Eevee7       True
Eevee8       True
Eevee9       True
Eevee10      True
Name: cp, dtype: bool

In [69]:
df.where(df['cp'] > 350)

cp      attack   attack_new
name                                    
Pidgey1   384.0  Aerial Ace   Air Cutter
Pidgey2   366.0     Twister   Air Cutter
Pidgey3   353.0  Aerial Ace   Air Cutter
Pidgey4     NaN         NaN          NaN
Pidgey5     NaN         NaN          NaN
Pidgey6     NaN         NaN          NaN
Pidgey7     NaN         NaN          NaN
Pidgey8     NaN         NaN          NaN
Pidgey9     NaN         NaN          NaN
Pidgey10    NaN         NaN          NaN
Eevee1    619.0   Body Slam    Aqua Tail
Eevee3    500.0         Dig   Fire Blast
Eevee7    606.0       Swift    Aqua Tail
Eevee8    548.0   Body Slam    Heat Wave
Eevee9    528.0         Dig  Thunderbolt
Eevee10   517.0   Body Slam    Heat Wave

In [70]:
hcp = df[df['cp'] > 370]
hcp

cp      attack   attack_new
name                                 
Pidgey1  384  Aerial Ace   Air Cutter
Eevee1   619   Body Slam    Aqua Tail
Eevee3   500         Dig   Fire Blast
Eevee7   606       Swift    Aqua Tail
Eevee8   548   Body Slam    Heat Wave
Eevee9   528         Dig  Thunderbolt
Eevee10  517   Body Slam    Heat Wave

In [72]:
df[ (df['cp'] > 370) & (df['attack']=='Dig') ]

cp attack   attack_new
name                           
Eevee3  500    Dig   Fire Blast
Eevee9  528    Dig  Thunderbolt

In [78]:
df.index

Index(['Pidgey1', 'Pidgey2', 'Pidgey3', 'Pidgey4', 'Pidgey5', 'Pidgey6',
       'Pidgey7', 'Pidgey8', 'Pidgey9', 'Pidgey10', 'Eevee1', 'Eevee3',
       'Eevee7', 'Eevee8', 'Eevee9', 'Eevee10'],
      dtype='object', name='name')

In [79]:
for idx in df.index:
    if idx[0] == 'E':
        df.rename(index={idx : 'fhp'+idx[5:]}, inplace=True)
df

cp      attack   attack_new
name                                  
Pidgey1   384  Aerial Ace   Air Cutter
Pidgey2   366     Twister   Air Cutter
Pidgey3   353  Aerial Ace   Air Cutter
Pidgey4   338  Air Cutter   Air Cutter
Pidgey5   242  Air Cutter      Twister
Pidgey6   129  Air Cutter   Aerial Ace
Pidgey7    10  Air Cutter   Air Cutter
Pidgey8    25     Twister   Air Cutter
Pidgey9    24     Twister      Twister
Pidgey10  161     Twister   Aerial Ace
fhp1      619   Body Slam    Aqua Tail
fhp3      500         Dig   Fire Blast
fhp7      606       Swift    Aqua Tail
fhp8      548   Body Slam    Heat Wave
fhp9      528         Dig  Thunderbolt
fhp10     517   Body Slam    Heat Wave